server:
  port: 8080
  servlet:
    context-path: /weeklyreport
spring:
  application:
    name: weeklyreport
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev

# ===== 自定义swagger配置 ===== #
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger 3.0整合Demo
  try-host: http://localhost:${server.port}


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/*.xml