server:
  port: 9080
  servlet:
    context-path: /weeklyreport
spring:
  application:
    name: weeklyreport
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev

# ===== 自定义swagger配置 ===== #
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger 3.0整合Demo
  try-host: http://localhost:${server.port}


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:mapper/*.xml

token:
  # 用于加密的密钥
  secret-key: YourSecretKey123
  # Token有效期（分钟）- 7天
  validity-minutes: 1080

wechat:
  appid: wxb92b2b0cb5c17a28
  secret: 31a9c9c3d2852f6642470c777a5edf8b